Repository alifsemi/zephyr_alif, pull requests merged in 2025-03, with the labels that each got.

#59 manifest: Update Hal alif
  west.yml
Labels: manifest, manifest-hal_alif

#57 manifest: Update HAL Alif
  west.yml
Labels: manifest, manifest-hal_alif

#60 manifest: update HAL Alif
  west.yml
Labels: manifest, manifest-hal_alif

#20 drivers: dma: add support for multiple instances.
  drivers/dma/dma_pl330.c
  drivers/dma/dma_pl330.h
Labels: area: DMA

#53 drivers: ipm: Update MHU driver
  drivers/ipm/ipm_arm_mhuv2.c
  drivers/ipm/ipm_arm_mhuv2.h
  include/zephyr/drivers/mhuv2_ipm.h
  west.yml
Labels: manifest, manifest-hal_alif, area: IPM
